### ISSUE TITLE
Health Component

### ISSUE THREAD

**Issue by UnoYakshi** [UnoYakshi/FPS-Prototype#10]
Both allies and foes should be able to die and to kill. It should be done via `UActorComponent` for better flexibility.
Though Batushka, for example, is protected by God, i.e., players' shots won't hurt him.

**Comment by andrew-it** [comment]
https://github.com/UnoYakshi/FPS-Prototype/pull/14

**Comment by UnoYakshi** [comment]
Added with PR #14.
